# syntax=docker/dockerfile:1

# ── Build stage ────────────────────────────────────────────────────────────
FROM node:20-alpine AS build
WORKDIR /app

# Install deps separately so layer caching works across source changes.
# `npm install` (not `npm ci`) so this builds even when the lockfile is
# briefly out-of-sync with package.json — switch to `npm ci` once the
# lockfile is reliably regenerated by CI.
COPY package.json package-lock.json* ./
RUN npm install --no-audit --no-fund

# Compile the SPA. VITE_API_URL bakes into the bundle at build time;
# default to the relative path so the runtime nginx /api/* proxy handles
# routing. Override at build time with --build-arg if you need a different
# value.
ARG VITE_API_URL=/api/v1
ENV VITE_API_URL=${VITE_API_URL}
COPY . .
RUN npm run build

# ── Runtime stage ──────────────────────────────────────────────────────────
# nginxinc/nginx-unprivileged runs entirely as the nginx user (no root
# master process) and listens on 8080 by default. Compatible with
# Kubernetes restricted PodSecurityStandards.
FROM nginxinc/nginx-unprivileged:1.27-alpine AS runtime

# Replace the default site config so we control everything.
USER root
RUN rm -f /etc/nginx/conf.d/default.conf
USER nginx

# Static assets.
COPY --chown=nginx:nginx --from=build /app/dist /usr/share/nginx/html

# nginx 1.19+ runs envsubst over /etc/nginx/templates/*.template at
# container start. We restrict the variable list so $host, $remote_addr,
# $proxy_add_x_forwarded_for etc. (which are nginx runtime variables, not
# env vars) are NOT mangled.
COPY --chown=nginx:nginx nginx/default.conf.template /etc/nginx/templates/default.conf.template
ENV NGINX_ENVSUBST_FILTER_VARIABLES="BACKEND_HOST NGINX_RESOLVER"
ENV BACKEND_HOST="api:8000"
# Docker's embedded DNS lives at 127.0.0.11. For Kubernetes set
# NGINX_RESOLVER to your cluster DNS (e.g., 10.96.0.10 or
# kube-dns.kube-system.svc.cluster.local).
ENV NGINX_RESOLVER="127.0.0.11"

EXPOSE 8080

# Container HEALTHCHECK — `wget --spider` returns 0 on 200, non-zero
# otherwise. nginx:alpine ships busybox wget.
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD wget --spider -q http://127.0.0.1:8080/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
